# Generated by Django 5.1.7 on 2026-03-31 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaInsumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Insumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("unidad", "Unidad"),
                            ("caja", "Caja"),
                            ("frasco", "Frasco"),
                            ("rollo", "Rollo"),
                            ("par", "Par"),
                            ("ml", "Mililitros"),
                            ("gr", "Gramos"),
                        ],
                        default="unidad",
                        max_length=10,
                    ),
                ),
                (
                    "stock_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(decimal_places=2, default=5, max_digits=10),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("proveedor", models.CharField(blank=True, max_length=200)),
                ("activo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario.categoriainsumo",
                    ),
                ),
            ],
            options={
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="MovimientoInventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida / Uso"),
                            ("ajuste", "Ajuste de inventario"),
                            ("vencido", "Baja por vencimiento"),
                        ],
                        max_length=10,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_resultante",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("motivo", models.CharField(blank=True, max_length=300)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "insumo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movimientos",
                        to="inventario.insumo",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
