# Generated by Django 5.1.7 on 2026-04-22 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoriainsumo",
            options={
                "ordering": ["nombre"],
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.AddField(
            model_name="insumo",
            name="fecha_vencimiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de vencimiento"
            ),
        ),
        migrations.AlterField(
            model_name="insumo",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario.categoriainsumo",
            ),
        ),
        migrations.AlterField(
            model_name="insumo",
            name="unidad",
            field=models.CharField(
                choices=[
                    ("unidad", "Unidad"),
                    ("caja", "Caja"),
                    ("frasco", "Frasco"),
                    ("rollo", "Rollo"),
                    ("par", "Par"),
                    ("ml", "Mililitros"),
                    ("gr", "Gramos"),
                    ("tableta", "Tableta"),
                    ("ampolla", "Ampolla"),
                    ("tubo", "Tubo"),
                    ("sobre", "Sobre"),
                    ("litro", "Litro"),
                    ("kg", "Kilogramo"),
                    ("jeringa", "Jeringa"),
                    ("guante", "Par de guantes"),
                ],
                default="unidad",
                max_length=10,
            ),
        ),
    ]
