# Generated by Django 5.1.7 on 2026-03-31 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaServicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("color", models.CharField(default="#22d3ee", max_length=7)),
            ],
            options={
                "verbose_name_plural": "Categorías de servicio",
            },
        ),
        migrations.CreateModel(
            name="HistoriaClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("motivo_consulta_inicial", models.TextField(blank=True)),
                ("antecedentes_medicos", models.TextField(blank=True)),
                ("antecedentes_dentales", models.TextField(blank=True)),
                ("habitos", models.TextField(blank=True)),
                ("fecha_apertura", models.DateField(auto_now_add=True)),
                (
                    "paciente",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historia",
                        to="pacientes.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotaClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("motivo", models.CharField(max_length=300)),
                ("hallazgos", models.TextField()),
                ("diagnostico", models.TextField()),
                ("plan_tratamiento", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "historia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notas",
                        to="clinico.historiaclinica",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Odontograma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odontogramas",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Servicio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duracion_minutos", models.IntegerField(default=30)),
                ("activo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clinico.categoriaservicio",
                    ),
                ),
            ],
            options={
                "ordering": ["categoria", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Tratamiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_diente", models.IntegerField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificado", "Planificado"),
                            ("en_proceso", "En proceso"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planificado",
                        max_length=15,
                    ),
                ),
                (
                    "precio_acordado",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("fecha_inicio", models.DateField(blank=True, null=True)),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("notas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tratamientos",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinico.servicio",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EstadoDiente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_diente", models.IntegerField()),
                (
                    "condicion",
                    models.CharField(
                        choices=[
                            ("sano", "Sano"),
                            ("caries", "Caries"),
                            ("obturado", "Obturado"),
                            ("extraido", "Extraído"),
                            ("corona", "Corona"),
                            ("implante", "Implante"),
                            ("endodoncia", "Endodoncia"),
                            ("fractura", "Fractura"),
                            ("puente", "Puente"),
                            ("ausente", "Ausente congénito"),
                            ("erupcion", "En erupción"),
                        ],
                        default="sano",
                        max_length=20,
                    ),
                ),
                (
                    "cara",
                    models.CharField(
                        choices=[
                            ("oclusal", "Oclusal"),
                            ("vestibular", "Vestibular"),
                            ("lingual", "Lingual/Palatino"),
                            ("mesial", "Mesial"),
                            ("distal", "Distal"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=15,
                    ),
                ),
                ("notas", models.CharField(blank=True, max_length=300)),
                ("color_hex", models.CharField(default="#22d3ee", max_length=7)),
                (
                    "odontograma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="estados",
                        to="clinico.odontograma",
                    ),
                ),
            ],
            options={
                "unique_together": {("odontograma", "numero_diente", "cara")},
            },
        ),
    ]
