# Generated by Django 5.1.7 on 2026-04-22 16:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EspacioClinico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(max_length=20, unique=True, verbose_name="Código"),
                ),
                ("nombre", models.CharField(max_length=150, verbose_name="Nombre")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("sillon", "Sillón dental"),
                            ("consultorio", "Consultorio general"),
                            ("rayos_x", "Sala de rayos X"),
                            ("esterilizacion", "Sala de esterilización"),
                            ("espera", "Sala de espera"),
                            ("cirugia", "Sala de cirugía"),
                            ("laboratorio", "Laboratorio"),
                            ("bodega", "Bodega"),
                            ("oficina", "Oficina"),
                            ("otro", "Otro"),
                        ],
                        default="sillon",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Piso / Ubicación"
                    ),
                ),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Capacidad (pacientes)"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#22d3ee",
                        max_length=7,
                        verbose_name="Color identificador",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("ocupado", "Ocupado"),
                            ("mantenimiento", "En mantenimiento"),
                            ("inactivo", "Inactivo"),
                        ],
                        default="disponible",
                        max_length=15,
                    ),
                ),
                (
                    "proxima_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima revisión"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="espacios_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Doctor asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Espacio clínico",
                "verbose_name_plural": "Espacios clínicos",
                "ordering": ["tipo", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="MantenimientoEspacio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("preventivo", "Mantenimiento preventivo"),
                            ("correctivo", "Mantenimiento correctivo"),
                            ("limpieza", "Limpieza profunda"),
                            ("inspeccion", "Inspección"),
                            ("reparacion", "Reparación de equipo"),
                            ("otro", "Otro"),
                        ],
                        default="preventivo",
                        max_length=15,
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Trabajo realizado")),
                (
                    "costo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "realizado_por",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Realizado por"
                    ),
                ),
                ("fecha", models.DateField(default=django.utils.timezone.now)),
                (
                    "proxima_revision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Próxima revisión"
                    ),
                ),
                (
                    "espacio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mantenimientos",
                        to="espacios.espacioclinico",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
    ]
