# Generated by Django 5.1.7 on 2026-04-22 17:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("espacios", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="espacioclinico",
            name="doctor_asignado",
        ),
        migrations.AddField(
            model_name="espacioclinico",
            name="doctores",
            field=models.ManyToManyField(
                blank=True,
                related_name="espacios_asignados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Doctores asignados",
            ),
        ),
        migrations.AlterField(
            model_name="espacioclinico",
            name="codigo",
            field=models.CharField(
                editable=False, max_length=20, unique=True, verbose_name="Código"
            ),
        ),
    ]
