# Generated by Django 5.1.7 on 2026-03-31 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Paciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        default="M",
                        max_length=1,
                    ),
                ),
                (
                    "ci",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="C.I.",
                    ),
                ),
                (
                    "tipo_sangre",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("?", "Desconocido"),
                        ],
                        default="?",
                        max_length=3,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("telefono_emergencia", models.CharField(blank=True, max_length=20)),
                ("contacto_emergencia", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("direccion", models.TextField(blank=True)),
                ("alergias", models.TextField(blank=True)),
                ("medicamentos_actuales", models.TextField(blank=True)),
                ("enfermedades_cronicas", models.TextField(blank=True)),
                ("observaciones", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="pacientes/fotos/"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paciente",
                "verbose_name_plural": "Pacientes",
                "ordering": ["apellidos", "nombres"],
            },
        ),
        migrations.CreateModel(
            name="Alergia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("medicamento", "Medicamento"),
                            ("material", "Material dental"),
                            ("alimento", "Alimento"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                ("reaccion", models.TextField(blank=True)),
                (
                    "gravedad",
                    models.CharField(
                        choices=[
                            ("leve", "Leve"),
                            ("moderada", "Moderada"),
                            ("severa", "Severa"),
                        ],
                        default="leve",
                        max_length=10,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lista_alergias",
                        to="pacientes.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdjuntoPaciente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("radiografia", "Radiografía"),
                            ("foto", "Fotografía clínica"),
                            ("documento", "Documento"),
                            ("consentimiento", "Consentimiento informado"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("archivo", models.FileField(upload_to="pacientes/adjuntos/%Y/%m/")),
                ("descripcion", models.TextField(blank=True)),
                ("fecha_subida", models.DateTimeField(auto_now_add=True)),
                (
                    "subido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjuntos",
                        to="pacientes.paciente",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_subida"],
            },
        ),
    ]
