# Generated by Django 5.1.7 on 2026-03-31 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinico", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoClinica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("antes", "Antes del tratamiento"),
                            ("durante", "Durante el tratamiento"),
                            ("despues", "Después del tratamiento"),
                            ("radiografia", "Radiografía"),
                            ("intraoral", "Foto intraoral"),
                            ("extraoral", "Foto extraoral"),
                            ("panoramica", "Radiografía panorámica"),
                            ("otro", "Otro"),
                        ],
                        max_length=15,
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("imagen", models.ImageField(upload_to="multimedia/fotos/%Y/%m/")),
                ("descripcion", models.TextField(blank=True)),
                ("fecha", models.DateField(auto_now_add=True)),
                ("numero_diente", models.IntegerField(blank=True, null=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fotos_clinicas",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "subido_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tratamiento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fotos",
                        to="clinico.tratamiento",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ComparacionFotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("fecha", models.DateField(auto_now_add=True)),
                ("notas", models.TextField(blank=True)),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comparaciones",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "foto_antes",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comp_antes",
                        to="multimedia.fotoclinica",
                    ),
                ),
                (
                    "foto_despues",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comp_despues",
                        to="multimedia.fotoclinica",
                    ),
                ),
            ],
        ),
    ]
