# Generated by Django 5.1.7 on 2026-03-31 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clinico", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MetodoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("activo", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha", models.DateField()),
                ("hora", models.TimeField(auto_now_add=True)),
                ("concepto", models.CharField(max_length=300)),
                ("numero_recibo", models.CharField(blank=True, max_length=50)),
                ("notas", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "metodo_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facturacion.metodopago",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pagos",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-hora"],
            },
        ),
        migrations.CreateModel(
            name="PlanPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_cuota", models.IntegerField()),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_vencimiento", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("pagado", "Pagado"),
                            ("vencido", "Vencido"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                ("fecha_pago", models.DateField(blank=True, null=True)),
                (
                    "pago",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="facturacion.pago",
                    ),
                ),
                (
                    "tratamiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_pagos",
                        to="clinico.tratamiento",
                    ),
                ),
            ],
            options={
                "ordering": ["tratamiento", "numero_cuota"],
            },
        ),
        migrations.CreateModel(
            name="Presupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("enviado", "Enviado"),
                            ("aceptado", "Aceptado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="borrador",
                        max_length=10,
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="presupuestos",
                        to="pacientes.paciente",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemPresupuesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_diente", models.IntegerField(blank=True, null=True)),
                ("cantidad", models.IntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinico.servicio",
                    ),
                ),
                (
                    "presupuesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="facturacion.presupuesto",
                    ),
                ),
            ],
        ),
    ]
