# Generated by Django 5.1.7 on 2026-04-01 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agenda", "0001_initial"),
        ("clinico", "0001_initial"),
        ("facturacion", "0001_initial"),
        ("inventario", "0001_initial"),
        ("pacientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("fecha", models.DateField(auto_now_add=True)),
                ("hora", models.TimeField(auto_now_add=True)),
                (
                    "descuento_global",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "descuento_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("pagado", "Pagado"), ("anulado", "Anulado")],
                        default="pagado",
                        max_length=10,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "cita",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="agenda.cita",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_doctor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "metodo_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facturacion.metodopago",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="pacientes.paciente",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets_registrados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha", "-hora"],
            },
        ),
        migrations.CreateModel(
            name="ItemTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("servicio", "Servicio"), ("producto", "Producto")],
                        max_length=10,
                    ),
                ),
                ("descripcion", models.CharField(max_length=300)),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.insumo",
                    ),
                ),
                (
                    "servicio",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="clinico.servicio",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="facturacion.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
    ]
