# Generated by Django 5.1.7 on 2026-03-31 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("admin", "Administrador"),
                            ("dentista", "Dentista"),
                            ("asistente", "Asistente"),
                            ("recepcion", "Recepcionista"),
                        ],
                        default="asistente",
                        max_length=15,
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("especialidad", models.CharField(blank=True, max_length=100)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="personal/fotos/"
                    ),
                ),
                ("color_agenda", models.CharField(default="#22d3ee", max_length=7)),
                ("activo", models.BooleanField(default=True)),
                (
                    "firma_digital",
                    models.ImageField(
                        blank=True, null=True, upload_to="personal/firmas/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
